### ISSUE TITLE
Проблема при скачивании объекта через вебклиент

### ISSUE THREAD

**Issue by Madbustazz** [InsecureBeast/Pilot.Web#24]
WEB-клиент выдаёт ошибку при скачивании объекта на диск
![unknown](https://user-images.githubusercontent.com/53031434/116544556-bcf5f400-a908-11eb-9f9a-50126f83640b.png)

**Comment by InsecureBeast** [comment]
Для решения проблемы приложите, пожалуйста, лог с сервера. (Logs/web_serever.log)

**Comment by Madbustazz** [comment]
[web_server.log](https://github.com/InsecureBeast/Pilot.Web/files/6459010/web_server.log)

**Comment by InsecureBeast** [comment]
Спасибо! Теперь понятна причина. Буду править.

**Comment by InsecureBeast** [comment]
> WEB-клиент выдаёт ошибку при скачивании объекта на диск
> ![unknown](https://user-images.githubusercontent.com/53031434/116544556-bcf5f400-a908-11eb-9f9a-50126f83640b.png)

Хочу уточнить эта ошибка воспроизводится на любом объекте? Т.е. невозможно скачать документ, исходный файл, папку целиком?

Какой браузер вы используете и какой версии?

**Comment by InsecureBeast** [comment]
В версии 20.2.0 ошибка исправлена
