### ISSUE TITLE
Авторизация LDAP

### ISSUE THREAD

**Issue by madrunner-ops** [InsecureBeast/Pilot.Web#30]
Доброго дня!
Можно ли изменить конфиг чтобы авторизоваться в Pilot-WEB могли не все пользователи Pilot-Server? 
В Pilot-Server у меня добавлены пользователи AD, хочется создать группу в AD, чтоб только пользователи из этой группу могли авторизоваться.

**Comment by InsecureBeast** [comment]
На данный момент такой возможности нет
